### model
model_name_or_path: /root/paddlejob/workspace/env_run/ws/weights/Qwen2.5-VL-7B-Instruct
total_min_pixels: 1605632 #2048*28*28
total_max_pixels: 3211264 #4096*28*28
video_maxlen: 64
video_fps: 1.0
# image_max_pixels: 262144
# video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

# additional_target: det_decoder,embed_tokens,merger
freeze_multi_modal_projector: true
freeze_vision_tower: true
gradient_checkpointing: true
disable_gradient_checkpointing: false

### dataset
dataset: mllm_demo,identity,alpaca_en_demo  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 16384
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl-7b/lora/sft_llm
logging_steps: 10
save_steps: 300
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### generate
max_new_tokens: 2048

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.01
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500